# --- Deployment ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
  namespace: simple-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      containers:
      - name: uptime-kuma
        image: louislam/uptime-kuma
        ports:
        - containerPort: 3001

---
# --- Service ---
apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma-service
  namespace: simple-http
spec:
  selector:
    app: uptime-kuma
  ports:
  - port: 8009
    targetPort: 3001
    protocol: TCP
  type: ClusterIP

---
# --- Ingress ---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptime-kuma-ingress
  namespace: simple-http
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/strip-path: "false"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - host: uptime.joshiharshal.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: uptime-kuma-service
            port:
              number: 8009
  tls:
    - hosts:
        - uptime.joshiharshal.cloud
      secretName: uptime-kuma-cert
